baseURL = "https://suksit.com/"
languageCode = "en-us"
title = "suksit dot com"
theme = "hello-friend-ng"
paginate = 10
copyright = "<a href=\"https://creativecommons.org/licenses/by-sa/4.0/\" target=\"_blank\">CC BY-SA 4.0</a>"

[author]
  name = "Suksit Sripitchayaphan"

[params]
  homeSubtitle = "Rant / Code / Note / Thought"
  enableThemeToggle = true
  customCSS = ["/css/custom.css"]

[params.logo]
  logoMark   = "$"
  logoText   = "cd /root"

[[menu.main]]
  identifier = "posts"
  name       = "Posts"
  url        = "/posts"
  weight     = 1

[[menu.main]]
  identifier = "about"
  name       = "About"
  url        = "/about"
  weight     = 2

[[params.social]]
  name = "twitter"
  url  = "https://twitter.com/suksit"

[[params.social]]
  name = "github"
  url  = "https://github.com/suksit"

[[params.social]]
  name = "linkedin"
  url  = "https://www.linkedin.com/in/suksit"

[[params.social]]
  name = "tryhackme"
  url  = "https://tryhackme.com/p/suksit"

[params.footer]
  trademark = true
  rss = true
  copyright = true
  author = true

  topText = []
  bottomText = ["Powered by <a href=\"http://gohugo.io\">Hugo</a>"]

[markup.goldmark.renderer]
  unsafe= true
