[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
TZ = "Asia/Bangkok"

[context.production.environment]
HUGO_VERSION = "0.125.7"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin"
    Permissions-Policy = "microphone=(), camera=()"
